apiVersion: v1
kind: Service
metadata:
  name: coffee-shop
  namespace: default
spec:
  selector:
    app: coffee-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP          # change to LoadBalancer if you need external access